/* D Citizens School Attendance — Firebase starter.
   1) Put your Firebase config in FIREBASE_CONFIG below.
   2) Enable Email/Password Auth, Firestore and Storage.
*/
const FIREBASE_CONFIG={apiKey:"PASTE_API_KEY",authDomain:"PASTE_PROJECT.firebaseapp.com",projectId:"PASTE_PROJECT",storageBucket:"PASTE_PROJECT.appspot.com",messagingSenderId:"PASTE_SENDER_ID",appId:"PASTE_APP_ID"};
let db,auth,storage,user;
const $=id=>document.getElementById(id), today=new Date().toISOString().slice(0,10);
$('today').textContent=today;$('attDate').value=today;$('reportMonth').value=today.slice(0,7);
function init(){if(FIREBASE_CONFIG.apiKey.startsWith('PASTE')){$('loginMsg').textContent='Add Firebase config in js/app.js first.';return}firebase.initializeApp(FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();storage=firebase.storage();auth.onAuthStateChanged(u=>{user=u;$('login').classList.toggle('hidden',!!u);$('app').classList.toggle('hidden',!u);if(u){loadStudents();loadAttendance()}})}
$('loginBtn').onclick=async()=>{try{await auth.signInWithEmailAndPassword($('email').value,$('password').value)}catch(e){$('loginMsg').textContent=e.message}};$('logout').onclick=()=>auth.signOut();
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));function showPage(p){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(p).classList.remove('hidden');$('pageTitle').textContent=p==='attendance'?'Take Attendance':p[0].toUpperCase()+p.slice(1);if(p==='reports')loadReports()}
$('addStudent').onclick=()=>{$('modal').classList.remove('hidden');['sGr','sName','sClass','sFather','sPhone'].forEach(x=>$(x).value='');$('sPhoto').value=''};$('closeModal').onclick=()=>$('modal').classList.add('hidden');
let students=[];async function loadStudents(){const snap=await db.collection('students').orderBy('name').get();students=snap.docs.map(d=>({id:d.id,...d.data()}));renderStudents();fillClasses();updateStats()}
function fillClasses(){let vals=[...new Set(students.map(s=>s.className).filter(Boolean))];$('classFilter').innerHTML='<option value="">All classes</option>'+vals.map(v=>`<option>${esc(v)}</option>`).join('')}
function renderStudents(){let q=$('studentSearch').value.toLowerCase();let arr=students.filter(s=>(s.name+' '+s.gr+' '+s.className).toLowerCase().includes(q));$('studentList').innerHTML=arr.map(s=>`<div class="row"><img src="${s.photo||''}" onerror="this.style.visibility='hidden'"><div><b>${esc(s.name)}</b><div class="muted">GR: ${esc(s.gr)} • ${esc(s.className||'')}</div></div><div>${esc(s.father||'')}</div><div>${esc(s.phone||'')}</div></div>`).join('')||'<div class="card">No students found.</div>'}
$('studentSearch').oninput=renderStudents;
$('saveStudent').onclick=async()=>{let file=$('sPhoto').files[0], photo='';if(!$('sGr').value||!$('sName').value){alert('GR number and name are required');return}if(file){let ref=storage.ref('student-photos/'+crypto.randomUUID());await ref.put(file);photo=await ref.getDownloadURL()}await db.collection('students').add({gr:$('sGr').value.trim(),name:$('sName').value.trim(),className:$('sClass').value.trim(),father:$('sFather').value.trim(),phone:$('sPhone').value.trim(),photo,createdAt:firebase.firestore.FieldValue.serverTimestamp()});$('modal').classList.add('hidden');loadStudents()};
async function loadAttendance(){let date=$('attDate').value||today;let snap=await db.collection('attendance').where('date','==',date).get();let map={};snap.forEach(d=>map[d.data().studentId]=d.data());let filter=$('classFilter').value;let arr=students.filter(s=>!filter||s.className===filter);$('attList').innerHTML=arr.map(s=>{let a=map[s.id]||{};return `<div class="row"><img src="${s.photo||''}" onerror="this.style.visibility='hidden'"><div><b>${esc(s.name)}</b><div class="muted">GR: ${esc(s.gr)} • ${esc(s.className||'')}</div></div><select data-id="${s.id}" class="status"><option value="present" ${a.status==='present'?'selected':''}>Present</option><option value="absent" ${a.status==='absent'?'selected':''}>Absent</option></select><button class="capture" data-id="${s.id}">📷 Live Photo</button></div>`}).join('')||'<div class="card">Add students first.</div>';document.querySelectorAll('.capture').forEach(b=>b.onclick=()=>captureFor(b.dataset.id))}
$('attDate').onchange=loadAttendance;$('classFilter').onchange=loadAttendance;
$('saveAll').onclick=async()=>{let batch=db.batch();document.querySelectorAll('.status').forEach(sel=>batch.set(db.collection('attendance').doc(`${sel.dataset.id}_${$('attDate').value}`),{studentId:sel.dataset.id,date:$('attDate').value,status:sel.value,markedBy:user.uid,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}));await batch.commit();alert('Attendance saved.');updateStats()};
async function captureFor(id){let input=document.createElement('input');input.type='file';input.accept='image/*';input.capture='environment';input.onchange=async()=>{let f=input.files[0];if(!f)return;let ref=storage.ref(`attendance-photos/${$('attDate').value}/${id}.jpg`);await ref.put(f);let url=await ref.getDownloadURL();await db.collection('attendance').doc(`${id}_${$('attDate').value}`).set({photo:url},{merge:true});alert('Live photo saved.');};input.click()}
async function updateStats(){let snap=await db.collection('attendance').where('date','==',today).get();let present=0; snap.forEach(d=>{if(d.data().status==='present')present++});$('total').textContent=students.length;$('present').textContent=present;$('absent').textContent=Math.max(students.length-present,0);$('rate').textContent=students.length?Math.round(present/students.length*100)+'%':'0%'}
async function loadReports(){let month=$('reportMonth').value||today.slice(0,7);let start=month+'-01',end=new Date(new Date(start).getFullYear(),new Date(start).getMonth()+1,1).toISOString().slice(0,10);let snap=await db.collection('attendance').where('date','>=',start).where('date','<',end).get();let counts={};snap.forEach(d=>{let a=d.data();counts[a.studentId]??={p:0,a:0};a.status==='present'?counts[a.studentId].p++:counts[a.studentId].a++});$('reportList').innerHTML=students.map(s=>{let c=counts[s.id]||{p:0,a:0},total=c.p+c.a,pct=total?Math.round(c.p/total*100):0;return `<div class="row"><div>${esc(s.gr)}</div><div><b>${esc(s.name)}</b><div class="muted">${esc(s.className||'')}</div></div><div>${c.p} P / ${c.a} A</div><div class="pill">${pct}%</div></div>`}).join('')||'<div class="card">No report data.</div>'}
$('reportMonth').onchange=loadReports;$('exportCsv').onclick=()=>{let rows=[['GR No','Name','Class','Present','Absent','Percentage']];document.querySelectorAll('#reportList .row').forEach(r=>{let cells=[...r.children].map(x=>x.innerText.replace(/\n/g,' '));rows.push(cells)});let csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='attendance-report.csv';a.click()};
function esc(x=''){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}init();
